/**
 * Copyright (c) 2005-2010 Zauber S.A. <http://www.zauber.com.ar/>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ar.com.zauber.commons.web.uri.assets;

import java.io.IOException;

import javax.servlet.jsp.JspException;
import javax.servlet.jsp.JspWriter;
import javax.servlet.jsp.tagext.Tag;

import org.springframework.web.context.WebApplicationContext;

import ar.com.zauber.commons.web.uri.SpringBeans;
import ar.com.zauber.commons.web.uri.factory.UriFactory;

/**
 * Prints an image url using an image key.
 * 
 * <p>The URIs generated by image inclusion are procesed by an instance of
 * {@link UriFactory}. This instance is acceced as a Spring Bean with name
 * as defined by {@link SpringBeans#ASSET_URIFACTORY_KEY}.
 * 
 * @author Mariano Cortesi
 * @since Dec 14, 2009
 */
public class ImageTag extends AbstractSpringTag {

    /** <code>serialVersionUID</code> */
    private static final long serialVersionUID = -3624874122306975946L;

    private String key;

    /** @see javax.servlet.jsp.tagext.TagSupport#doStartTag() */
    @Override
    public final int doStartTag() throws JspException {
        WebApplicationContext appCtx = getApplicationContext();
        UriFactory uriFactory = appCtx.getBean(SpringBeans.ASSET_URIFACTORY_KEY,
                UriFactory.class); 
        
        JspWriter out = this.pageContext.getOut();
        try {
            out.write(uriFactory.buildUri(this.key));
        } catch (IOException e) {
            throw new JspException(e);
        }

        return Tag.SKIP_BODY;
    }

    public final void setKey(final String key) {
        this.key = key;
    }

}
